project:
  type: website

website:
  title: "ML for Dummies"
  navbar:
    logo: images/logo.png  # Ajoutez votre logo ici
    left:
      - href: index.qmd
        text: 🏠 Home
      - href: index1.qmd
        text: ✏️ Hands-on
      - href: index2.qmd
        text: 📊 K-means
    right:
      - href: https://github.com/JoaoBabadoudou
        icon: github
      - href: about.qmd
        text: ℹ️ About
  sidebar:
    style: "floating"
    search: true
    contents:
      - href: index.qmd
        text: 🏠 Home
      - href: index1.qmd
        text: ✏️ Hands-on
      - href: index2.qmd
        text: 📊 K-means
      - href: about.qmd
        text: ℹ️ About

format:
  html:
    theme:
      light: minty  # Design plus moderne et épuré
      dark: superhero
    css: styles.css  # Fichier CSS personnalisé
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    smooth-scroll: true
    grid:
      sidebar-width: 250px
      body-width: 850px  # Un peu plus large pour un meilleur affichage
      margin-width: 300px
