project:
  type: website

website:

     favicon: "D:/R_projet/NeuralR/Quato_/LOGO1.png"
     title: "The Perceptron"
     navbar:
       left:
       - href: index.qmd
         text: Home
       
       -  href: index1.qmd
          text: Hands-on
       right : 
        
       -  href: https://github.com/JoaoBabadoudou
          icon: github
       - about.qmd  
           

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



