{
  "hash": "838d8d7e760051dfb5901cb6a190dc74",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hands-on\"\n---\n\n\n\n\nLet's start with an example.\n\nLet's suppose that we have two kind of plant that we have to divide into two classes: **toxic** plants represented by class **0** and **healthy** plants represented by class **1**. Each plant has his characteristics **X1** and **X2**. The following table show us what it is about:\n\n| Y  |X1 | X2|\n|----|---|---|\n| 1  |0.5| 2 |\n| 1  |1.1|2.1|\n| 1  |0.7|2.6|\n| 1  |2  | 1 |\n| 1  |2.5|0.7|\n| 1  |2.2|0.3|\n\nLet' us have a better look with a graphic\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nx1= c(0.5,1.1,0.7,2,2.5,2.2)\nx2=c(2,2.1,2.6,1,0.7,0.3)\ny= factor(c(1,1,1,0,0,0), levels=c(0,1))\nY=factor(y)\ndata= data.frame(cbind(y,x1,x2)  ) \nggplot(data = data, aes(x = x1, y = x2)) +\n  geom_point(aes(colour = Y), size = 3) + \n  scale_colour_manual(values = c(\"red\", \"green\")) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index1_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n\n\nAs we can see, we can provide a line that can separate the two kinds of plant. This line is **the decision boundary**. So we're able to develop a model, based on this line to predict the class of a new plant.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nx1= c(0.5,1.1,0.7,2,2.5,2.2,1.5)\nx2=c(2,2.1,2.6,1,0.7,0.3,0.5)\ny= factor(c(1,1,1,0,0,0,2), levels=c(0,1,2))\nY=factor(y)\ndata= data.frame(cbind(y,x1,x2)  ) \nggplot(data = data, aes(x = x1, y = x2)) +\n  geom_point(aes(colour = Y), size = 3) + \n  scale_colour_manual(values = c(\"red\", \"green\", \"blue\")) + \n  geom_abline(slope = 1, intercept = 0.1, colour = \"black\", size = 1.2) + # Boundary line\n  labs(title = \"Data separation\", x = \"x1\", y = \"x2\") + \n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index1_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n\n\n\nTo de velop the model, we need to know the equation of the line that separate accuratly the two plants. To achieve this, we'll develop a linear model by sending **X1** and **X2** to a neuron, adding a coefficient **W**, respectively **W1** and **W2** and what we call the bias **b**. It'll lead us to :\n\n$$  z(X1,X2)= W1*X1 + W2*X2 + b   $$\n\n\n\nThe boundary line is the value for which $$ Z(X_1,X_2)=0$$   So by posing $Z(X_1,X_2)=0$, we can find the expression of the equation of the boundary line.\nTo predict a class for a new  plant, we have to  set the parameters $ W_1 $, $ W_2 $  and  $b$  to separe in the best way the two class and after that we will be able to send a new plant according to the sign of the $Z$ computed. \nNow, to improve this model, one of the best thing that we can do is to add probabilities. The further the plant is from the line, the greater the chance that it belongs to this class. In this context, we use an **activation function** that returns a value close to 0 or 1 as we move away from the line. Generally we use the sigmoiid fonction.\n\nThe **sigmoid function** is one of the most common activation functions in artificial neural networks, especially in simpler or shallow models. It maps any real-valued number to a range between **0 and 1**, making it particularly useful for binary classification problems.\n\n\nThe **sigmoid function** $a(Z)$ is defined as:\n\n$a(Z) = \\frac{1}{1 + e^{-Z}}$\n\n\n\nWhere:\n\n- $e$ is the base of the natural logarithm (approximately 2.718).\n-  $Z$ is the input to the function, which can be any real number.\n\n\n\nThe graph of the sigmoid function has an **S-shape** (sigmoid curve) and is asymptotic to both 0 and 1 for extreme values of \\( x \\). \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n# Define sigmoid function\nsigmoid <- function(x) {\n  return(1 / (1 + exp(-x)))\n}\nx_values <- seq(-10, 10, by = 0.1)\ny_values <- sigmoid(x_values)\n# Create a data frame for plotting\ndata <- data.frame(x = x_values, y = y_values)\n\n# Plot the sigmoid curve with color differentiation for both the curve and area under it\nggplot(data, aes(x = x, y = y)) +\n  geom_line(size = 1.5, color = \"black\") +  # Black line for sigmoid curve\n  geom_ribbon(data = subset(data, x < 5), aes(ymin = y, ymax = 1), fill = \"lightblue\", alpha = 0.5) +  # Light blue for the left part under and on the curve\n  geom_ribbon(data = subset(data, x >=-5 ), aes(ymin = 0, ymax = y), fill = \"lightcoral\", alpha = 0.5) +  # Light red for the right part under the curve\n  labs(title = \"Sigmoid Function \", x = \"x\", y = \"Sigmoid(x)\") +\n  theme_minimal() +\n  theme(axis.title = element_text(size = 12), plot.title = element_text(size = 14, hjust = 0.5))\n```\n\n::: {.cell-output-display}\n![](index1_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\n\n\n**Defining the Cost Function**\n\nTo find the best model, we need to minimize the error between the predictions and the real values. This process involves using the sigmoid function to derive probabilities, leveraging the Bernoulli probability function, and defining the likelihood and log-likelihood functions, that we call the log-loss function which is defined as\n$$\\ell(W_1, W_2, b) = -1/n[\\sum_{i=1}^n \\left[ Y_i \\cdot \\log(a(z_i)) + (1 - Y_i) \\cdot \\log(1 - a(z_i)) \\right]]$$\n\nLet us have a better view on how we got this.\nThe likelihood function measures how well the model predicts the entire dataset. To find it, we can just make the product of all the probabilities that we compute using the sigmoid function for each plants.\n For \\( n \\) observations, it is defined as:\n\n$$L(W_1, W_2, b) = \\prod_{i=1}^n P(Y_i|X_i)$$\n\nS\n\n$$P(Y_i|X_i)$$\n\nThe sigmoid function transforms a linear combination of features into probabilities, defined as:\n$a(z) = \\frac{1}{1 + e^{-z}}$\n\n\nwhere:\n\n$z = W_1 \\cdot X_1 + W_2 \\cdot X_2 + b$\n\nHere,  $W_1$ , $W_2$, and $b$  are the parameters of the model, and  $X_1$,  $X_2$  are the input features.\n\n\n\nThe Bernoulli distribution models the likelihood of binary outcomes $Y \\in \\{0, 1\\}$. The probability for a single observation is:\n\n$P(Y|X) = a(z)^Y \\cdot (1 - a(z))^{1-Y}$\nwhere:\n $a(z)$ is the predicted probability of $Y = 1$,\n $1 - a(z)$ is the predicted probability of $Y = 0$\n\n\nSubstituting the Bernoulli probability function, the likelihood becomes:\n\n$$L(W_1, W_2, b) = \\prod_{i=1}^n \\left[ a(z_i)^{Y_i} \\cdot (1 - a(z_i))^{1-Y_i} \\right]$$\n\nIf the result of this calculation is 0.99, for example, this means that our model is 99% plausible. Conversely, if the result is close to 0, it would mean that our model is highly implausible. Let us apply it to our data\n\n\n\n::: {.cell}\n\n:::\n\n\n\nThe probability are:\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n  Probability\n1   0.8320184\n2   0.7502601\n3   0.8807971\n4   0.2890505\n5   0.1544653\n6   0.1418511\n```\n\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.003482233\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index1_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n\nThe likelihood value is `0.003482233`.\nIn fact, this is the prduct of probability\n\n$L= 0.8320184 * 0.7502601 * 0.8807971 * 0.2890505 * 0.1544653 * 0.1418511$\n\nLet's remark that the likelihood is very low. Can we really deduce that the model is'nt likely. Imagine that we have more than 10000 lines. The product of all the probability can lead to a number extremely close to 0, at some point, the machine will no longer be able to store the value.\nThat's why we use the log-likelihood.\n\n**Log-Likelihood Function**\n\nTo simplify computation and avoid numerical underflow, we use the log-likelihood, which is the natural logarithm of the likelihood:\n\n$$\\ell(W_1, W_2, b) = \\log L(W_1, W_2, b)$$\n\nExpanding this, we get:\n\n$$\\ell(W_1, W_2, b) = \\sum_{i=1}^n \\left[ Y_i \\cdot \\log(a(z_i)) + (1 - Y_i) \\cdot \\log(1 - a(z_i)) \\right]$$\n\nIn fact, the log function is monotonically increasing. It therefore preserves order. This means that $a<b$ implies that $log(a)<log(b)$\nMeaning that to maximize the likelyhood of the model, we just need to maximize the log-likelihood.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index1_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n\nGenerally, it can be a little bit difficult to maximise a mathematical  function. So by multiplying the log like lihood by (-), our aim will be the minimisation of the loglikelihood function .\n$maximising f(x)$ is equal to $minimise -f(x)$\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index1_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n\nWe addd also the term 1/N to normalise our answer. This is how the log loss function is gotten.\n\n$$\\ell(W_1, W_2, b) = -1/n[\\sum_{i=1}^n \\left[ Y_i \\cdot \\log(a(z_i)) + (1 - Y_i) \\cdot \\log(1 - a(z_i)) \\right]]$$\n\n\n\nAnd there you have it, you now know where cost fomction comes from. Now we're going to use the cost funcion to minimise the errors of the model, using the **Gradient descent**.\n\n**Gradient descent**\n\n",
    "supporting": [
      "index1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}